services:
  mysql:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ephemera_memory
      MYSQL_USER: ephemera_ai
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql

  qdrant:
    image: "qdrant/qdrant:latest"
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mysql_data:
  qdrant_data:
